# Default values for helm-web-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # uncomment and fill registry name
  registry: shirito
  name: helm-web-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000

namespace: default

# for the ingress functionallity - the ingress is the controller which exposes the newly deployed service
# Refer to the docs for more details
ingress:
  ingressNamespace: default
  minPort: 20000
  maxPort: 30000
  ingressLabel: ingress
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: localhost
      paths:
        - path: /helm/(.*)
          port: 4000

# configuration for the rbac namespaces, service accounts, roles and binding names
rbac:
  helmServiceAccount: helm
  helmRole: tiller-user
  tillerServiceAccount: tiller
  tillerRoleBindingName: tiller-user-binding
  tillerNamespace: kube-system
