{{- if .Values.rabbitmq.communityPlugins -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.fullname" . }}-plugins
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  install-plugins.sh: |
    #!/bin/bash
    echo "==> Plugin installation"
    echo $RABBITMQ_PLUGINS_DIR
    pluginPath=/opt/bitnami/rabbitmq/plugins
    {{- $totalPlugins := len .Values.rabbitmq.communityPlugins }}
    echo "Total plugins defined in chart installation: {{ $totalPlugins }}"
    {{- range $i, $plugin := .Values.rabbitmq.communityPlugins }}
    echo "Installing plugin {{ add $i 1 }} out of {{ $totalPlugins }}: {{ $plugin }}"
    pluginUrl={{ $plugin }}
    # remove the version number from the plugin name
    pluginName=$(echo ${pluginUrl##*/} | sed "s/\-.*//")
    curl -X GET $pluginUrl -L -o $pluginPath/$pluginName.ez
    rabbitmq-plugins enable $pluginName
    {{- end }}
    echo "==> End of Plugin installation"
{{- end -}}
